import { defineNuxtPlugin } from '#app'
import {
  CheckBadgeIcon,
  ArrowUpCircleIcon,
  ArrowUpOnSquareIcon,
  AtSymbolIcon,
  Bars3Icon,
  CalendarIcon,
  CameraIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  DevicePhoneMobileIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  EyeIcon,
  IdentificationIcon,
  HeartIcon,
  MinusCircleIcon,
  MoonIcon,
  PaperClipIcon,
  PencilIcon,
  PencilSquareIcon,
  PlusCircleIcon,
  QrCodeIcon,
  RocketLaunchIcon,
  SunIcon,
  SparklesIcon,
  UserCircleIcon,
  XCircleIcon,
  XMarkIcon,
  CakeIcon,
  ArrowRightEndOnRectangleIcon,
  BriefcaseIcon,
  DocumentPlusIcon,
  DocumentMagnifyingGlassIcon,
  PlusIcon,
  TrashIcon,
  RectangleGroupIcon,
  Cog6ToothIcon,
  BuildingLibraryIcon,
} from '@heroicons/vue/24/solid'

export default defineNuxtPlugin((nuxtApp) => {
  const icons = {
    BuildingLibraryIcon,
    DocumentMagnifyingGlassIcon,
    PlusIcon,
    DocumentPlusIcon,
    BriefcaseIcon,
    ArrowUpCircleIcon,
    ArrowUpOnSquareIcon,
    AtSymbolIcon,
    Bars3Icon,
    CalendarIcon,
    CameraIcon,
    CheckCircleIcon,
    ChevronDownIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    ChevronLeftIcon,
    DevicePhoneMobileIcon,
    DocumentTextIcon,
    EnvelopeIcon,
    EyeIcon,
    HeartIcon,
    IdentificationIcon,
    MinusCircleIcon,
    MoonIcon,
    PaperClipIcon,
    PencilIcon,
    PencilSquareIcon,
    PlusCircleIcon,
    QrCodeIcon,
    RocketLaunchIcon,
    SunIcon,
    SparklesIcon,
    UserCircleIcon,
    XCircleIcon,
    XMarkIcon,
    CakeIcon,
    ArrowRightEndOnRectangleIcon,
    TrashIcon,
    RectangleGroupIcon,
    Cog6ToothIcon,
    CheckBadgeIcon,
  }

  Object.entries(icons).forEach(([name, component]) => {
    if (!nuxtApp.vueApp.component(name)) {
      nuxtApp.vueApp.component(name, component)
    }
  })
})
